name: Model-Training Deployment

on:
  workflow_dispatch:
    inputs:
      bump_level:
        description: 'Specify the type of version bump for the new release.'
        required: false
        type: choice 
        options:   
          - patch
          - minor
          - major
        default: 'patch' 

jobs:
  delivery:
    name: Deployment
    runs-on: ubuntu-latest
    env:
      CLASSIFIER_MODEL_FILENAME: c2_Classifier_Sentiment_Model.joblib
      BOW_MODEL_FILENAME: c1_BoW_Sentiment_Model.pkl
      MODEL_DIRECTORY: ./models

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump stable version and push tag
        id: bump_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          pre_release_branches: 'NONE'
          default_bump: ${{ inputs.bump_level }}
          tag_prefix: v

      - name: Create GitHub Release Page Entry
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.bump_version.outputs.new_tag  }}
          name: Release ${{ steps.bump_version.outputs.new_tag  }}
          body: |
            Automated release for model version **${{ steps.bump_version.outputs.new_tag  }}**.

            **Classifier Model Artifact:** `${{ env.CLASSIFIER_MODEL_FILENAME }}`
            **BoW Model Artifact:** `${{ env.BOW_MODEL_FILENAME }}`

            **Download the models from the following links:**
            - Classifier Model Artifact: https://github.com/remla25-team5/model-training/releases/download/${{ steps.bump_version.outputs.new_tag  }}/${{ env.CLASSIFIER_MODEL_FILENAME }}
            - BoW Model Artifact: https://github.com/remla25-team5/model-training/releases/download/${{ steps.bump_version.outputs.new_tag  }}/${{ env.BOW_MODEL_FILENAME }}
            
          files: |
            ${{ env.MODEL_DIRECTORY }}/${{ env.CLASSIFIER_MODEL_FILENAME }}
            ${{ env.MODEL_DIRECTORY }}/${{ env.BOW_MODEL_FILENAME }}


      - name: Add new pre release
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: 'NONE'
          pre_release_branches: main
          default_prerelease_bump: prerelease
          append_to_pre_release_tag: pre
          tag_prefix: v